// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugins/kotlin-serialization/kotlin-serialization-compiler/src/class_extensions.proto

package libetal.kotlinx.serialization.compiler.extensions;

import org.jetbrains.kotlin.metadata.*
import org.jetbrains.kotlin.protobuf.ExtensionRegistryLite
import org.jetbrains.kotlin.protobuf.GeneratedMessageLite

public final class SerializationPluginMetadataExtension {

    companion object {
        @JvmStatic
        val PROPERTIES_NAMES_IN_PROGRAM_ORDER_FIELD_NUMBER = 18000;

        @JvmStatic
        fun registerAllExtensions(registry: ExtensionRegistryLite) {
            registry.add(propertiesNamesInProgramOrder);
        }


        @JvmStatic
        val propertiesNamesInProgramOrder: GeneratedMessageLite.GeneratedExtension<ProtoBuf.Class, List<Int>> =
            GeneratedMessageLite.newRepeatedGeneratedExtension(
                ProtoBuf.Class.getDefaultInstance(),
                null,
                null,
                18000,
                org.jetbrains.kotlin.protobuf.WireFormat.FieldType.INT32,
                false,
                java.lang.Integer::class.java
            )
    }
}