// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugins/kotlin-serialization/kotlin-serialization-compiler/src/class_extensions.proto

package org.jetbrains.kotlinx.serialization.compiler.extensions;

public final class SerializationPluginMetadataExtension {

    companion object {
        @JvmStatic
        val PROPERTIES_NAMES_IN_PROGRAM_ORDER_FIELD_NUMBER = 18000;

        @JvmStatic
        fun registerAllExtensions(registry: org.jetbrains.kotlin.protobuf.ExtensionRegistryLite) {
            registry.add(propertiesNamesInProgramOrder);
        }


        @JvmStatic
        val propertiesNamesInProgramOrder: org.jetbrains.kotlin.protobuf.GeneratedMessageLite.GeneratedExtension<
                org.jetbrains.kotlin.metadata.ProtoBuf.Class, List<Int>> = org.jetbrains.kotlin.protobuf.GeneratedMessageLite
            .newRepeatedGeneratedExtension(
                org.jetbrains.kotlin.metadata.ProtoBuf.Class.getDefaultInstance(),
                null,
                null,
                18000,
                org.jetbrains.kotlin.protobuf.WireFormat.FieldType.INT32,
                false,
                java.lang.Integer::class.java
            )
    }
}